development:
  host: localhost
  database: make_my_cv_development

test:
  host: localhost
  database: make_my_cv_test

# set these environment variables on your prod server
production:
  host: staff.mongohq.com
  port: 10022
  username: amardaxini
  password: thakkar!
  database: makemycv
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019
